config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: "users/registrations" }
  resources :user_events
  resources :events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "home#index"
  get '/home' => "home#home"

  get '/browse_outdoors' => "home#browse_outdoors"
  get '/browse_kayaking' => "home#browse_kayaking"
  get '/browse_rafting' => "home#browse_rafting"
  get '/browse_sailing' => "home#browse_sailing"
  get '/browse_hiking' => "home#browse_hiking"
  get '/browse_climbing' => "home#browse_climbing"
  get '/browse_fishing' => "home#browse_fishing"
  get '/browse_hunting' => "home#browse_hunting"
  get '/browse_camping' => "home#browse_camping"
  get '/browse_surfing' => "home#browse_surfing"
  get '/browse_skiing' => "home#browse_skiing"
  get '/browse_snowboarding' => "home#browse_snowboarding"
  get '/browse_mountainbiking' => "home#browse_mountainbiking"
  get '/browse_walking' => "home#browse_walking"
  get '/browse_fitness' => "home#browse_fitness"
  get '/browse_running' => "home#browse_running"
  get '/browse_cycling' => "home#browse_cycling"
  get '/browse_swimming' => "home#browse_swimming"
  get '/browse_baseball' => "home#browse_baseball"
  get '/browse_basketball' => "home#browse_basketball"
  get '/browse_soccer' => "home#browse_soccer"
  get '/browse_football' => "home#browse_football"
  get '/browse_hockey' => "home#browse_hockey"
  get '/browse_lacrosse' => "home#browse_lacrosse"
  get '/browse_softball' => "home#browse_softball"
  get '/browse_dance' => "home#browse_dance"
  get '/browse_zumba' => "home#browse_zumba"
  get '/browse_yoga' => "home#browse_yoga"
  get '/browse_pilates' => "home#browse_pilates"
  get '/browse_recreation' => "home#browse_recreation"
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
	belongs_to :user
	belongs_to :event

	enum status: [:upcoming, :past, :wishlist]
end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController
  before_action :set_user_event, only: [:show, :edit, :update, :destroy]

  # GET /user_events
  # GET /user_events.json
  def index
    @user_events = UserEvent.all
  end

  # GET /user_events/1
  # GET /user_events/1.json
  def show
  end

  # GET /user_events/new
  def new
    @user_event = UserEvent.new
  end

  # GET /user_events/1/edit
  def edit
  end

  # POST /user_events
  # POST /user_events.json
  def create
    @user_event = UserEvent.new(user_event_params)

    respond_to do |format|
      if @user_event.save
        format.html
        format.json
      else
        format.html { render :new }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_events/1
  # PATCH/PUT /user_events/1.json
  def update
    respond_to do |format|
      if @user_event.update(user_event_params)
        format.html { redirect_to @user_event, notice: 'User event was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_event }
      else
        format.html { render :edit }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_events/1
  # DELETE /user_events/1.json
  def destroy
    @user_event.destroy
    respond_to do |format|
      format.html 
      format.json 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_event
      @user_event = UserEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_event_params
      params.require(:user_event).permit(:user_id, :event_id, :status)
    end
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/views/user_events/_form.html.erb
<%= form_with(model: user_event, local: true) do |form| %>
  <% if user_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_event.errors.count, "error") %> prohibited this user_event from being saved:</h2>

      <ul>
      <% user_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_events/edit.html.erb
<h1>Editing User Event</h1>

<%= render 'form', user_event: @user_event %>

<%= link_to 'Show', @user_event %> |
<%= link_to 'Back', user_events_path %>

app/views/user_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Events</h1>

<table>
  <thead>
    <tr>
      <th>References</th>
      <th>References</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_events.each do |user_event| %>
      <tr>
        <td><%= link_to 'Show', user_event %></td>
        <td><%= link_to 'Edit', edit_user_event_path(user_event) %></td>
        <td><%= link_to 'Destroy', user_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Event', new_user_event_path %>

app/views/user_events/new.html.erb
<h1>New User Event</h1>

<%= render 'form', user_event: @user_event %>

<%= link_to 'Back', user_events_path %>

app/views/user_events/show.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Edit', edit_user_event_path(@user_event) %> |
<%= link_to 'Back', user_events_path %>